trunk/Universal Containers - ORG/src/AppExchange Laboratory Recruiting App Components/objects/Position__c.object
<CustomObject>
    <description>This is change #5 on Position object</description>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/Sanbox/src/unpackaged/classes/PositionSharingClassTest.cls
public class PositionSharingClassTest {
	private static testMethod void myShareTest(){
		// this is a test method for Position Inserts, not Updates
		// updates were left out so as not to interfere with student helloWorldTest exercise
		Position__c[] positions = new Position__c[100];
		
		for (Integer i=0;i<100;i++){
			positions[i] = new Position__c();
			
			positions[i].Name = String.valueOf(i) + ' test name';
			positions[i].Responsibilities__c = String.valueOf(i) + ' test responsibilities';
			positions[i].Job_Description__c = String.valueOf(i) + ' test description';
		}
		
		try{
			System.debug('attempting to update the position');
			insert positions;
			System.debug('update complete');
		} catch (System.DmlException e){
			System.debug('we caught a dml exception: ' + e.getDmlMessage(0));	
		}
	}
}